config/routes.rb
Rails.application.routes.draw do
  resources :artists
  resources :songs

  root to: 'pages#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  has_many :songs, dependent: :destroy

  validates :name, presence: true, uniqueness: true, length: { maximum: 50}
  validates :age, presence: true, uniqueness: false, length: { maximum: 3}
  validates :img_url, presence: true, uniqueness: false, length: { maximum: 100}

  def change
    create_table  :artists do |t|
      t.string    :name
      t.integer   :age
      t.string    :img_url

      t.timestamps
    end
  end
end

app/models/photo.rb
class Photo < ApplicationRecord
	validates :img_url, presence: true
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :artist
	has_and_belongs_to_many :photos
	
	validates :title,	presence: true, uniqueness: false
	validates :artist, presence: true, uniqueness: false
	validates :description, presence: true, length: {maximum: 500}
	validates :year, presence: true, uniqueness: false, length: {maximum: 4}
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  
  def index
    @artists = Artist.all
  end
    
  def show
    @artist = Artist.find(params[:id])
  end
    
  def new
    @artist = Artist.new
  end
    

  def create
    @artist = Artist.new(artist_params)

    if @artist.save
      redirect_to @artist
    else
      render 'new'
    end      
  end
    
  def edit
    @artist = Artist.find(params[:id])
  end

  def update
    @artist = Artist.find(params[:id])

    if @artist.update_attributes(artist_params)
      redirect_to @artist, notice: "Artist updated!"
    else
      render 'edit'
    end
  end

  def destroy
    @artist = Artist.find(params[:id])

    @artist.destroy

    redirect_to artists_path, notice: "Artist deleted!"
  end

  private

  def find_artist
    @artist = Artist.find(params[:id])
  end

  def artist_params
    params.require(:artist).permit(:name, :age, :img_url)
  end
    

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController

	def index
    @songs = Song.all
 	end
	
 	def new
    @song = Song.new
 	end
  
 	def create
    @artist = Artist.find_by_name(params[:song][:artist])
    @song = Song.new(song_params.merge(artist: @artist))

    respond_to do |format|
      if @song.save
        format.html { redirect_to artist_path(@artist), notice: "Song saved!" }
        format.json { render :show, status: :created, location: @song }
      else
        format.html { render :new }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end   
 	end
    
 	def edit
    @song = Song.find(params[:id])
 	end

 	def update
    @song = Song.find(params[:id])

    if @song.update_attributes(song_params)
      redirect_to @song, notice: "Song updated!"
    else
      render :edit
    end
 	end

	def show
		@song = Song.find(params[:id])
		@artist = Artist.find(@song.artist.id)
	end
	
 	def destroy
    @song = Song.find(params[:id])
    @artist = Artist.find(@song.artist.id)

    @song.destroy

    respond_to do |format|
      format.html { redirect_to songs_path, notice: "Song deleted!" }
      format.json { render :show, status: :deleted, location: @artist }
    end 

    
 	end

 	private
	
	def song_params
		params.require(:song).permit(:title, :description, :year)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/artists/_form.html.erb
<%= form_for @artist do |x| %>

  <ul>
    <% @artist.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
  </ul>
  <%= x.label :name %>
  <%= x.text_field :name %>

  <%= x.label :age %>
  <%= x.number_field :age %>

  <%= x.label :"Image URL" %>
  <%= x.text_field :img_url %>

  <%= x.submit (@artist.new_record? ? "Add new Artist" : "Update Artist") %>
<% end %>

app/views/artists/edit.html.erb
<h1>Edit Artist</h1>

<%= render "form" %>

app/views/artists/index.html.erb
<h1> Our best artists</h1>

<div class="artist-container">
<% @artists.each do |artist| %>
    <div class="artist"><h3><%= link_to artist.name, artist_path(artist) %></h3>
        <%= image_tag artist.img_url %></div>
<% end %>
</div>
<br> 


<br>
<footer>
	<%= link_to "All Songs", songs_path %>
	<%= link_to "Create New Artist", new_artist_path %>
</footer>

app/views/artists/new.html.erb
<h1>New Artist</h1>


<%= render 'form' %>

app/views/artists/show.html.erb
<div class="artists artist-flex">
	<div class="artist-big">
		<%= image_tag @artist.img_url %>  
  </div>
	<div class="container-data">
  <br>
	<h2><%= @artist.name %></h2>
		<hr>
	<h4>Age: <%= @artist.age %></h4>
		<br>
		<br>
		
		
<h3>All songs in repository:</h3>
	<div class="repository-songs">
    <% if @artist.songs.present? %>
    <ul>
        <% @artist.songs.each do |song| %>
            <li> 
            	<%= link_to song.title, song_path(song), id: song.id, class: 'song' %> 
            	<button class='delete_song btn btn-link btn-sm'> &#10006; </button>
            </li>
        <% end %>
    </ul>
    <br>
    <br>
    <button class='delete_all_songs btn btn-danger btn-sm'> Delete all songs </button>
  <% else %>
    <p> This artist has any songs yet :( </p>
  <% end %>
		</div>
	</div>
</div>



<footer>
	<%= link_to "All artists", artists_path(@artist) %>
  <%= link_to "Add new artist", new_artist_path %>
	<%= link_to "Add new song", new_song_path %>
  <%= link_to "Edit this artist", edit_artist_path(@artist) %>
  <%= link_to "Delete this artist", artist_path(@artist), method: :delete, data: {confirm: "Are you sure to delete this artist and all his songs?"} %>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Urify amazing app</title>
    <link href="https://fonts.googleapis.com/css?family=Cabin" rel="stylesheet">
		<link href="https://fonts.googleapis.com/css?family=Black+Ops+One|Rubik+Mono+One" rel="stylesheet">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <!-- Static navbar -->
  <%= render 'shared/navbar' %>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <div class="brutal">
    <p class="three">u r i f</p>
    <p class="four">y + + +</p>
  </div>

    <div>
    <%= yield %>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<div class="box">
	<h1> Amazing Uriffy App <br><small>Your perfect songs & artists collection</small></h1>
	<br>
	<br>
	<button class="main-button btm btn-lg btn-danger"><%= link_to "Discover music", artists_path %></button>
	<br>
	<br>
	<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin nibh augue, suscipit a, scelerisque sed, lacinia in, mi. Cras vel lorem. Etiam pellentesque aliquet tellus. Phasellus pharetra nulla ac diam. Quisque semper justo at risus. Donec venenatis, turpis vel hendrerit interdum, dui ligula ultricies purus, sed posuere libero dui id orci. Nam congue, pede vitae dapibus aliquet, elit magna vulputate arcu, vel tempus metus leo non est. Etiam sit amet lectus quis est congue mollis. Phasellus congue lacus eget neque. Phasellus ornare, ante vitae consectetuer consequat, purus sapien ultricies dolor, et mollis pede metus eget nisi. Praesent sodales velit quis augue. Cras suscipit, urna at aliquam rhoncus, urna quam viverra nisi, in interdum massa nibh nec erat.</p>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-inverse navbar-static-top">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand">Urify App</a>
      	<p class="navbar-brand button-main"><%= link_to "Start", root_path %>
        <p class="navbar-brand button-main"><%= link_to "Discover music", artists_path %></p>
    </div>
  </div>
</nav>

app/views/songs/_form.html.erb
<%= form_with do |x| %>
  <ul>
    <% @song.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
  </ul>
  <%= x.label :title %>
  <%= x.text_field :title, :id => "song_title" %>

	<%= x.label :artist %>
  <%= x.text_field :artist, :id => "song_artist" %>

  <%= x.label :description %>
  <%= x.text_field :description, :id => "song_description" %>

  <%= x.label :year %>
  <%= x.number_field :year, :id => "song_year" %>

  <%= x.submit (@song.new_record? ? "Add new song" : "Update song"), :id => "form_submit"  %>
<% end %>

app/views/songs/_form_ajax.html.erb
<%= form_for @song, html: {remote: true} do |x| %>

  <ul>
    <% @song.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
  </ul>
  <%= x.label :title %>
  <%= x.text_field :title %>

	<%= x.label :artist %>
  <%= x.text_field :artist %>

  <%= x.label :description %>
  <%= x.text_field :description %>

  <%= x.label :year %>
  <%= x.number_field :year %>

  <button><%= 'Add new song' %></button>
<% end %>

app/views/songs/edit.html.erb
<h1>Edit Song</h1>

<%= render "form" %>

app/views/songs/index.html.erb
<h1>All songs repository:</h1>

<div class="songs-container">
  <% @songs.each do |song| %>
   
	<ul class="songs">
		
		<h3><%= link_to song.title, song_path(id: song.id, artist_id: song.artist.id) %>, by <%= song.artist.name %></h3>
			
  </ul>
   <% end %>
</div>

<footer>
	<%= link_to "All Artists", artists_path %>
  <%= link_to "Add new song", new_song_path %>
</footer>

app/views/songs/new.html.erb
<h1>New song</h1>

<%= render 'form' %>

app/views/songs/show.html.erb
<h1> <%= @song.title %></h1>
<div class="details-song">
	<p><strong> Title: </strong> <%= @song.title %></p>
	<p><strong> Description:</strong> <%= @song.description %></p>
	<p><strong> Release year:</strong> <%= @song.year %></p>
</div>
<footer>
	<%= link_to "All songs", songs_path(@artist) %>
  <%= link_to "Add new song", new_song_path %>
	<%= link_to "Edit song description", edit_song_path(@song.id) %>
	<%= link_to "Delete song", song_path(id: @song.id), method: :delete, data: {confirm: "Are you sure to delete this song?" } %>
</footer>